### ISSUE TITLE
Personal (at least for now) Modification

### ISSUE THREAD

**Issue by plebejer1** [SiegeEngineers/WololoKingdoms#19]
Dear Developers of WololoKingdoms,

I really enjoy your work, playing it on voobly with a few friends of mine.
I hope this is the right way to contact you, but I couldn't find a forum or anything along those lines.
Now I've made a little private modification to yours, namely a triple tech version, and am wondering about how I'll move from now.
First of all - my action wasn't illegal i presume?
Since I haven't released the mod, I shouldn't have infringed upon any copyrights. At least that is the conclusion I came to with my limited understanding nowadays. 
Secondly - since I had a few ideas moving forward (different Tech levels (3x, 9x, 256x), multiplication of civ-bonuses or Fun stuff like Feitoria-Effect for everyone) I was thinking it might be a nice Idea to publish this mod on voobly when I'm finished.
I would never do this of course, if anyone related to your project is against my intention.
Unregarding the answer, I would like to thank you for all the work you've put into this.
It's really nice to be able to play the new dlc civs on voobly, especially since my best friend can't run the HD version with more than 8 fps.

Hoping for a positive reply,

plebejer

**Comment by Jineapple** [comment]
For your personal use, you can do of course whatever you want without issue.

If you want to publish these mods, you need to be careful. The WK installer checks if the person running it owns the DLCs on steam. If you distribute your mods (e.g. with the voobly mod center) without the check of the installer, you'd be distributing copyrighted files.
However, the installer has an extra option for data mods based on WK. This already includes x3 and x9 mods by the way. If you have any extra mods that you want included, you can create an issue and ask for it to be included in the official distribution.
