### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by pumukelaoe** [SiegeEngineers/WololoKingdoms#58]
Just bought a new computer, installed Rise of Rajas on Steam, installed Voobly. When I start WololoKingdoms.exe, this window appears after the Update Check: https://prnt.sc/s1gvpd

What can I do?

**Comment by Jineapple** [comment]
Did you start Age2HD? It requires some extra libraries that are installed on first start I believe. Also try verifying your game files.

If those two steps don't help, I would have to look into it further.

**Comment by pumukelaoe** [comment]
Yes, I did a test game in Age2HD.

Also, with verifying game files, you mean this? https://prnt.sc/s1hu2y

**Comment by Jineapple** [comment]
Yeah, I assume it still doesn't work? Can you check the folder of the installer for prelog.txt and log.txt and paste their content here?

**Comment by pumukelaoe** [comment]
> Yeah, I assume it still doesn't work?

Yes, still the same https://prnt.sc/s1gvpd

> Can you check the folder of the installer for prelog.txt and log.txt and paste their content here?

prelog.txt is empty.

log.txt is:

0ms - NewRun
HD Path:C:\Program Files (x86)\Steam\steamapps\common\Age2HD
AoC Path:c:\program files (x86)\microsoft games\age of empires ii\Voobly Mods\AOC\Data Mods\WololoKingdoms
Patch mode: -1
DLC level: 3
1ms - Check for symlink
0ms - Removing base folders
9ms - Creating base folders
2ms - Removing language.ini
17ms - Replace tooltips
159ms - convert language file
216ms - index DRS files
424ms - Visual Mod Stuff
39ms - History Files
36ms - Civ Intro Sounds
6ms - Create Music Playlist
1ms - Copy Taunts
282ms - Copy Scenario Sounds
7834ms - Write expansion XML
7ms - Copy Voobly Map folder
114ms - Copy Special Maps
1ms - Copying AI
77ms - Hotkey Setup
0ms - Opening dats
759ms - HUD Hack
13ms - Transfer HD Dat elements
97ms - Patch Architectures
388ms - Opening DRS
0ms - Make DRS c:\program files (x86)\microsoft games\age of empires ii\Voobly Mods\AOC\Data Mods\WololoKingdoms\Data\gamedata_x1_p1.drs
22825ms - Make random map scripts DRS
568ms - DAT Patches
19ms - Save DAT
744ms - Create Hash
209ms - Offline installation symlink
9669ms - FE Setup
4ms - AK Setup
5ms - Create Offline Exe

**Comment by gregstein** [comment]
Hello there,

I recommend you to install this all in one vc pack: http://m.majorgeeks.com/files/details/visual_c_runtime_installer.html

While installing some vc++ redistro may already be installed but instead of skipping choose to repair them.

Now exit steam and run steam as admin. 
Then run AoE2 HD and make sure it runs.
Now run WK installer as admin too and try again.

Still fails? 99% your graphic card driver (is it AMD ? then disable "Vari-bright" under powerplay options). it's recommended to Install latest drivers for best stability.

**Comment by pumukelaoe** [comment]
Thanks, Greg! Is this advice coordinated with Jineapple?

**Comment by gregstein** [comment]
> Thanks, Greg! Is this advice coordinated with Jineapple?
> 
> Btw my graphic card is https://prnt.sc/s1wlep

That's a relief.

> Is this advice coordinated with Jineapple?

No, Just a wild guest because certainly the issue resides in your system not the installer. Let us how that worked out <3

**Comment by pumukelaoe** [comment]
Looks like installing the VC++s worked: https://prnt.sc/s1zyw8

Also HD Single Player worked after that.

But when installing WK, same old https://prnt.sc/s1gvpd

**Comment by gregstein** [comment]
> Looks like installing the VC++s worked: https://prnt.sc/s1zyw8
> 
> Also HD Single Player worked after that.
> 
> But when installing WK, same old https://prnt.sc/s1gvpd

Ok that's a good progress. 

I have some doubt that your system is not allowing apps to use over 2 GB of ram so my suggestion to increase that by running CMD as admin and typing in:
`bcedit /set IncreaseUserVA 3072`

Reboot your computer and now let's try different approach to install wk installer through exe file from here:
https://github.com/AoE2CommunityGitHub/WololoKingdoms/releases/tag/5.8.1

Then give it a shot hopefully it'll work for you.

Later on If you feel that your ram is being used heavily by some programs I suggest to revert the change back to default by running CMD as admin again and typing in:
`bcdedit /deletevalue IncreaseUserVa`

**Comment by pumukelaoe** [comment]
Like this? https://prnt.sc/s2g9n0

**Comment by scomans** [comment]
I'm having the same issue on Win10 🤔 All the above did not help.
I tried 5.8.1 and also the 5.9 Beta

Edit: After using AoE2Tools once and uninstalling it after that it started working 😖

**Comment by pete9516** [comment]
@Jineapple @gregstein I've tried everything you provided here. None of the above worked. And i never had AoE2Tools installed. Is it that maybe WololoKingdoms doesn't support Windows 7 or something like that?

**Comment by gregstein** [comment]
@pete9516 Hello Pete,

I just pushed a new update to WKcloud installer for AoE2Tools. I recommend you to install the latest version of AoE2Tools https://github.com/gregstein/AoE2Tools/releases/tag/3.3.3.0 

Then **Right click AoE2Tools shield** > WKCloud installer
![I7wDmoZ-SMS_haeuF5oXbQ 1](https://user-images.githubusercontent.com/16618729/172683182-549b7111-bd4d-4bea-b65c-b0843c421b9d.png)

Minimum system requirement (as far as i have tested in the past) for WK is Windows 7 Ultimate or Professional. I recommend Ultimate. AoE2Tools will install WK regardless whether it runs or not on your system just be sure to have .NET 4.5 at least or higher.

**Comment by pete9516** [comment]
That doesn't really help me. Because the thing is that WololoKingdoms simply won't work. I even use Ultimate and NET Framework 4.5 or higher. And i downloaded the latest version of WololoKingdoms. As far as i know. If AoE2Tools can make WK to work i won't lose time downloading it, but at the moment i think that it won't really help me. :/ btw does somebody know  where i can get the 1.4 version of the UserPatch? All links lead to the new 1.5 version..

**Comment by pete9516** [comment]
> I'm having the same issue on Win10 thinking All the above did not help. I tried 5.8.1 and also the 5.9 Beta
> 
> Edit: After using AoE2Tools once and uninstalling it after that it started working confounded

Well i may try that one out yet, but i'm curious if it works just because i install aoe2tools and uninstall it.. I will post if it has worked or not

**Comment by pete9516** [comment]
It has worked to just install AoE2Tools and to reinstall it. Thanks again
